# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8f26990826e75f31fe2b0f5adb49ccdddfea1bd80fe4f186088514cdde01b972db6712db1c759cc2b9ad38efca9f34b6616adc95d27a9c246a7e1b19435aa6e

test:
  secret_key_base: d4f28806ca8c54ecd118b1709706dc945a257e0c308678396190897cf0a514e316e07cb0f57f02c926d714332007c55ae4992bc71dbe11e49313da3769aa1554

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
